[package]
name = "tasklist-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tasklist-domain = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
time = { workspace = true }
utoipa = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
