[package]
name = "tasklist-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tasklist-domain = { workspace = true }
tasklist-application = { workspace = true }
async-trait = { workspace = true }
time = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
